"""create shares table

Revision ID: 04c5d51c9eb8
Revises: aaff82dfdac7
Create Date: 2026-09-18 00:17:18.251376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c5d51c9eb8'
down_revision: Union[str, None] = 'aaff82dfdac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shares',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('resource_type', sa.String(length=10), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('shared_with_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("permission IN ('viewer', 'editor')", name='ck_permission'),
    sa.CheckConstraint("resource_type IN ('file', 'folder')", name='ck_resource_type'),
    sa.CheckConstraint('owner_id != shared_with_id', name='ck_not_self_share'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type', 'resource_id', 'shared_with_id', name='uq_share_resource_user')
    )
    op.create_index(op.f('ix_shares_resource_id'), 'shares', ['resource_id'], unique=False)
    op.create_index(op.f('ix_shares_shared_with_id'), 'shares', ['shared_with_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shares_shared_with_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_resource_id'), table_name='shares')
    op.drop_table('shares')
    # ### end Alembic commands ###
